#ifndef _SYSTEM_CONFIG_H_
#define _SYSTEM_CONFIG_H_

// DHT22 Configuration
#define DHT22_PIN GPIO_NUM_4

#define SENTINEL_TEMP_FIRE_THRESHOLD_C     45.0f
#define SENTINEL_HUMIDITY_LOW_THRESHOLD_PCT 25.0f
#define SENTINEL_TEMP_RATE_CRITICAL 10.0f
#define SENTINEL_TEMP_RATE_HIGH      5.0f
#define SENTINEL_TEMP_RATE_MEDIUM    2.0f
#define SENTINEL_TEMP_RATE_LOW       0.5f


// HC-SR04
#define HC_SR04_TRIG_PIN 5
#define HC_SR04_ECHO_PIN 18

#define SENTINEL_WATER_REFERENCE_HEIGHT_CM 100.0f



#endif